[package]
name = "radium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
image = "0.24.6"
lazy_static = "1.4.0"
log = "0.4.19"
nalgebra-glm = "0.18.0"
pretty_env_logger = "0.5.0"
serde = "1.0.175"
serde_json = "1.0.103"
thiserror = "1.0.44"
tobj = "4.0.0"
vulkanalia = { version = "0.21.0", features = ["libloading", "provisional", "window"] }
winit = "0.28.6"
